import type { Metadata } from "next";
import localFont from "next/font/local";
//import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/toaster"
import {ModeToggle} from "@/components/ui/modo-toggle"

// const geistSans = localFont({
//     src: "../fonts/GeistVF.woff",
//     variable: "--font-geist-sans",
//     weight: "100 900",
// });
// const geistMono = localFont({
//     src: "../GeistMonoVF.woff",
//     variable: "--font-geist-mono",
//     weight: "100 900",
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // <html lang="en" suppressHydrationWarning={true}>
        // <body
        //     className={`antialiased`}
        // >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
        {/*<ModeToggle/>*/}
        <SidebarProvider>
          <AppSidebar />
        <main className={'mt-4 h-full w-full'}>
            <SidebarTrigger />
            {children}
        </main>
        </SidebarProvider>
            <Toaster />
        </ThemeProvider>
        //</body>
        //</html>
    );
}
